package generate

import (
	"fmt"
	"math"
	"strings"
)

// GCodeOutput holds the generated G-code, optionally split by tool.
type GCodeOutput struct {
	Combined string
	BallEnd  string
	VBit     string
}

// GenerateGCode produces G-code for the board.
func GenerateGCode(board *Board) *GCodeOutput {
	p := board.Params
	out := &GCodeOutput{}

	// Origin offset: if CornerOrigin, shift all coords so (0,0) is
	// at the bottom-left corner of the board's bounding circle.
	ox, oy := 0.0, 0.0
	if p.CornerOrigin {
		ox = p.BoardDiameter / 2
		oy = p.BoardDiameter / 2
	}

	var combined strings.Builder
	var ballEnd strings.Builder
	var vbit strings.Builder

	originLabel := "Center of board"
	if p.CornerOrigin {
		originLabel = "Board corner (0,0 at bottom-left)"
	}

	writeHeader := func(w *strings.Builder, title string) {
		fmt.Fprintf(w, "%%\n")
		fmt.Fprintf(w, "(Wahoo! Board Game - %s)\n", title)
		fmt.Fprintf(w, "(Generated by Magravation GCode Generator)\n")
		fmt.Fprintf(w, "(Board: %.1f\" dia round, Marble: %.3f\", Grid: %.4f\")\n",
			p.BoardDiameter, p.MarbleDiameter, p.GridSpacing())
		fmt.Fprintf(w, "(Pocket: %.4f\" dia x %.4f\" deep, Players: %d)\n",
			p.HoleDiameter(), p.HoleDepth(), p.NumPlayers)
		fmt.Fprintf(w, "(Origin: %s)\n", originLabel)
		if p.DrawBorder {
			fmt.Fprintf(w, "(Border: %.3f\" radius, %.4f\" deep, 0.125\" wide)\n",
				p.BorderRadius(), p.BorderDepth())
		}
		fmt.Fprintf(w, "G20 (Inches)\n")
		fmt.Fprintf(w, "G90 (Absolute positioning)\n")
		fmt.Fprintf(w, "G17 (XY plane)\n")
		fmt.Fprintf(w, "G40 (Cancel cutter compensation)\n")
		fmt.Fprintf(w, "G49 (Cancel tool length offset)\n")
		fmt.Fprintf(w, "\n")
	}

	writeFooter := func(w *strings.Builder) {
		fmt.Fprintf(w, "G0 Z%.4f (Retract to safe height)\n", p.SafeZ)
		fmt.Fprintf(w, "M5 (Spindle off)\n")
		fmt.Fprintf(w, "G0 X%.4f Y%.4f (Return to origin)\n", ox, oy)
		fmt.Fprintf(w, "M30 (Program end)\n")
		fmt.Fprintf(w, "%%\n")
	}

	// Combined file header
	writeHeader(&combined, "All Operations")

	// ========================================
	// TOOL 1: Ball End Mill - Marble Holes
	// ========================================
	writeHeader(&ballEnd, fmt.Sprintf("Ball End Mill %.4f\" - Marble Holes", p.BallEndDiameter))

	for _, w := range []*strings.Builder{&combined, &ballEnd} {
		fmt.Fprintf(w, "(=== TOOL 1: %.4f\" Ball End Mill - Marble Holes ===)\n", p.BallEndDiameter)
		fmt.Fprintf(w, "T1 M6 (Tool change: 1/4\" Ball End Mill)\n")
		fmt.Fprintf(w, "M3 S%d (Spindle on)\n", p.SpindleSpeed)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.SafeZ)
		fmt.Fprintf(w, "\n")
	}

	holeGroups := []struct {
		name  string
		htype HoleType
	}{
		{"Center Hole", HoleCenter},
		{"Home Row Holes", HoleHomeRow},
		{"Track Holes", HoleTrack},
		{"Start Position Holes", HoleStart},
		{"Base Holes", HoleBase},
	}

	for _, group := range holeGroups {
		holes := filterHoles(board.Holes, group.htype)
		if len(holes) == 0 {
			continue
		}

		for _, w := range []*strings.Builder{&combined, &ballEnd} {
			fmt.Fprintf(w, "(--- %s: %d holes ---)\n", group.name, len(holes))
		}

		for i, hole := range holes {
			comment := fmt.Sprintf("Hole %d/%d %s", i+1, len(holes), group.name)
			if hole.Player >= 0 {
				comment += fmt.Sprintf(" P%d", hole.Player+1)
			}
			gcodeMarbleHole(&combined, hole, p, ox, oy, comment)
			gcodeMarbleHole(&ballEnd, hole, p, ox, oy, comment)
		}
	}

	for _, w := range []*strings.Builder{&combined, &ballEnd} {
		fmt.Fprintf(w, "\nG0 Z%.4f (Retract)\n", p.SafeZ)
		fmt.Fprintf(w, "M5 (Spindle off)\n\n")
	}
	writeFooter(&ballEnd)

	// ========================================
	// TOOL 2: V-Bit - Text Engraving + Border
	// ========================================
	writeHeader(&vbit, fmt.Sprintf("%.0f° V-Bit - Text & Border", p.VBitAngle))

	for _, w := range []*strings.Builder{&combined, &vbit} {
		fmt.Fprintf(w, "(=== TOOL 2: %.0f° V-Bit - Text Engraving ===)\n", p.VBitAngle)
		fmt.Fprintf(w, "T2 M6 (Tool change: 60 degree V-Bit)\n")
		fmt.Fprintf(w, "M3 S%d (Spindle on)\n", p.SpindleSpeed)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.SafeZ)
		fmt.Fprintf(w, "\n")
	}

	for _, text := range board.TextItems {
		strokes := TextToStrokes(text.Text, text.X, text.Y, text.Height, text.Angle, text.CenterOn)
		comment := fmt.Sprintf("Text: \"%s\"", text.Text)

		for _, w := range []*strings.Builder{&combined, &vbit} {
			fmt.Fprintf(w, "(%s)\n", comment)
		}

		for _, stroke := range strokes {
			if len(stroke) < 2 {
				continue
			}
			for _, w := range []*strings.Builder{&combined, &vbit} {
				fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", stroke[0].X+ox, stroke[0].Y+oy)
				fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
				fmt.Fprintf(w, "G1 Z%.4f F%.1f\n", -p.TextDepth, p.FeedRateZ)
				for j := 1; j < len(stroke); j++ {
					fmt.Fprintf(w, "G1 X%.4f Y%.4f F%.1f\n", stroke[j].X+ox, stroke[j].Y+oy, p.FeedRateXY)
				}
				fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
			}
		}
	}

	// Border circle
	if p.DrawBorder {
		borderR := p.BorderRadius()
		borderD := p.BorderDepth()

		for _, w := range []*strings.Builder{&combined, &vbit} {
			fmt.Fprintf(w, "\n(--- Border Circle: radius %.3f\", depth %.4f\", width 0.125\" ---)\n", borderR, borderD)
			// Position at (borderR, 0) relative to center
			fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", borderR+ox, oy)
			fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
			fmt.Fprintf(w, "G1 Z%.4f F%.1f\n", -borderD, p.FeedRateZ)
			// Full circle CCW: I = -borderR (offset to center), J = 0
			fmt.Fprintf(w, "G3 X%.4f Y%.4f I%.4f J%.4f F%.1f\n",
				borderR+ox, oy, -borderR, 0.0, p.FeedRateXY)
			// Spring pass
			fmt.Fprintf(w, "G3 X%.4f Y%.4f I%.4f J%.4f F%.1f\n",
				borderR+ox, oy, -borderR, 0.0, p.FeedRateXY)
			fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
		}
	}

	for _, w := range []*strings.Builder{&combined, &vbit} {
		fmt.Fprintf(w, "\n")
	}
	writeFooter(&vbit)
	writeFooter(&combined)

	out.Combined = combined.String()
	out.BallEnd = ballEnd.String()
	out.VBit = vbit.String()

	return out
}

func gcodeMarbleHole(w *strings.Builder, hole Hole, p Params, ox, oy float64, comment string) {
	toolRadius := p.BallEndDiameter / 2
	holeRadius := hole.Diameter / 2
	pocketRadius := holeRadius - toolRadius
	depth := hole.Depth
	hx := hole.X + ox
	hy := hole.Y + oy

	fmt.Fprintf(w, "(%s at X%.4f Y%.4f D%.4f Z%.4f)\n", comment, hx, hy, hole.Diameter, -depth)

	if pocketRadius <= 0.005 {
		fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", hx, hy)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
		currentZ := 0.0
		for currentZ > -depth {
			currentZ -= p.DepthPerPass
			if currentZ < -depth {
				currentZ = -depth
			}
			fmt.Fprintf(w, "G1 Z%.4f F%.1f\n", currentZ, p.FeedRateZ)
		}
		fmt.Fprintf(w, "G4 P0.5 (Dwell)\n")
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
	} else {
		startX := hx + pocketRadius
		startY := hy
		fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", startX, startY)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
		fmt.Fprintf(w, "G1 Z0.0 F%.1f\n", p.FeedRateZ)
		currentZ := 0.0
		for currentZ > -depth {
			nextZ := currentZ - p.DepthPerPass
			if nextZ < -depth {
				nextZ = -depth
			}
			fmt.Fprintf(w, "G3 X%.4f Y%.4f I%.4f J%.4f Z%.4f F%.1f\n",
				startX, startY, -pocketRadius, 0.0, nextZ, p.FeedRateXY)
			currentZ = nextZ
		}
		fmt.Fprintf(w, "G3 X%.4f Y%.4f I%.4f J%.4f F%.1f\n",
			startX, startY, -pocketRadius, 0.0, p.FeedRateXY)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
	}
}

func filterHoles(holes []Hole, htype HoleType) []Hole {
	var result []Hole
	for _, h := range holes {
		if h.Type == htype {
			result = append(result, h)
		}
	}
	return result
}

// GenerateSVG creates an SVG preview of the board layout.
func GenerateSVG(board *Board) string {
	p := board.Params
	margin := 0.5

	halfBoard := p.BoardDiameter / 2
	minX, minY := -halfBoard, -halfBoard
	maxX, maxY := halfBoard, halfBoard

	scale := 500.0 / (maxX - minX + 2*margin)
	svgW := (maxX - minX + 2*margin) * scale
	svgH := (maxY - minY + 2*margin) * scale

	toSvgX := func(x float64) float64 { return (x - minX + margin) * scale }
	toSvgY := func(y float64) float64 { return svgH - (y-minY+margin)*scale }

	var sb strings.Builder
	fmt.Fprintf(&sb, `<svg xmlns="http://www.w3.org/2000/svg" width="%.0f" height="%.0f" viewBox="0 0 %.0f %.0f">`, svgW, svgH, svgW, svgH)
	fmt.Fprintf(&sb, "\n")

	// Round board background
	cx := toSvgX(0)
	cy := toSvgY(0)
	boardR := (halfBoard - p.EdgeMargin()*0.3) * scale
	fmt.Fprintf(&sb, `<circle cx="%.1f" cy="%.1f" r="%.1f" fill="#D4A574" stroke="#8B6914" stroke-width="3"/>`,
		cx, cy, boardR)
	fmt.Fprintf(&sb, "\n")

	// Border circle (if enabled)
	if p.DrawBorder {
		borderSvgR := p.BorderRadius() * scale
		fmt.Fprintf(&sb, `<circle cx="%.1f" cy="%.1f" r="%.1f" fill="none" stroke="#6B4914" stroke-width="2" stroke-dasharray="4,2"/>`,
			cx, cy, borderSvgR)
		fmt.Fprintf(&sb, "\n")
	}

	holeColor := map[HoleType]string{
		HoleTrack:   "#4A4A4A",
		HoleBase:    "#2196F3",
		HoleHomeRow: "#4CAF50",
		HoleCenter:  "#FF9800",
		HoleStart:   "#F44336",
	}
	playerColor := []string{"#E53935", "#1E88E5", "#43A047", "#FDD835", "#AB47BC", "#FF7043"}

	for _, hole := range board.Holes {
		sx := toSvgX(hole.X)
		sy := toSvgY(hole.Y)
		sr := (hole.Diameter / 2) * scale

		color := holeColor[hole.Type]
		if hole.Type == HoleBase && hole.Player >= 0 && hole.Player < len(playerColor) {
			color = playerColor[hole.Player]
		}

		fmt.Fprintf(&sb, `<circle cx="%.1f" cy="%.1f" r="%.1f" fill="%s" stroke="#333" stroke-width="1" opacity="0.8"/>`,
			sx, sy, math.Max(sr, 3), color)
		fmt.Fprintf(&sb, "\n")
	}

	for _, text := range board.TextItems {
		sx := toSvgX(text.X)
		sy := toSvgY(text.Y)
		fontSize := text.Height * scale * 0.6
		anchor := "start"
		if text.CenterOn {
			anchor = "middle"
		}
		// SVG Y is flipped, so negate the rotation angle
		svgAngle := -text.Angle
		if text.Angle != 0 {
			fmt.Fprintf(&sb, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="%.1f" fill="#333" text-anchor="%s" transform="rotate(%.1f,%.1f,%.1f)">%s</text>`,
				sx, sy, fontSize, anchor, svgAngle, sx, sy, text.Text)
		} else {
			fmt.Fprintf(&sb, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="%.1f" fill="#333" text-anchor="%s">%s</text>`,
				sx, sy, fontSize, anchor, text.Text)
		}
		fmt.Fprintf(&sb, "\n")
	}

	legendX := 10.0
	legendY := svgH - 100
	legends := []struct{ color, label string }{
		{"#4A4A4A", "Track"}, {"#F44336", "Start"}, {"#4CAF50", "Home"},
		{"#FF9800", "Center"}, {"#2196F3", "Base"},
	}
	for i, leg := range legends {
		y := legendY + float64(i)*18
		fmt.Fprintf(&sb, `<rect x="%.0f" y="%.0f" width="12" height="12" fill="%s"/>`, legendX, y, leg.color)
		fmt.Fprintf(&sb, `<text x="%.0f" y="%.0f" font-family="sans-serif" font-size="11" fill="#333">%s</text>`, legendX+16, y+10, leg.label)
		fmt.Fprintf(&sb, "\n")
	}

	fmt.Fprintf(&sb, `<text x="%.0f" y="%.0f" font-family="sans-serif" font-size="11" fill="#666">Holes: %d | %d-Player | %.0f" dia</text>`,
		legendX, legendY-10, len(board.Holes), p.NumPlayers, p.BoardDiameter)
	fmt.Fprintf(&sb, "\n")

	fmt.Fprintf(&sb, "</svg>")
	return sb.String()
}
