package magravation

import (
	"fmt"
	"math"
	"strings"
)

// GCodeOutput holds the generated G-code, optionally split by tool.
type GCodeOutput struct {
	Combined string // single file with tool changes
	BallEnd  string // marble holes only (Tool 1)
	Straight string // dice pockets only (Tool 2)
	VBit     string // text engraving only (Tool 3)
}

// GenerateGCode produces G-code for the entire board.
func GenerateGCode(board *Board) *GCodeOutput {
	p := board.Params
	out := &GCodeOutput{}

	var combined strings.Builder
	var ballEnd strings.Builder
	var straight strings.Builder
	var vbit strings.Builder

	// --- File headers ---
	writeHeader := func(w *strings.Builder, title string) {
		fmt.Fprintf(w, "%%\n")
		fmt.Fprintf(w, "(Aggravation Board Game - %s)\n", title)
		fmt.Fprintf(w, "(Generated by Magravation GCode Generator)\n")
		fmt.Fprintf(w, "(Board: %.1f\" x %.1f\", Marble: %.3f\", Dice: %.3f\")\n",
			p.BoardSize, p.BoardSize, p.MarbleDiameter, p.DiceSize)
		fmt.Fprintf(w, "(Players: %d)\n", p.NumPlayers)
		if p.CenterOrigin {
			fmt.Fprintf(w, "(Origin: Center of board)\n")
		} else {
			fmt.Fprintf(w, "(Origin: Bottom-left corner)\n")
		}
		fmt.Fprintf(w, "G20 (Inches)\n")
		fmt.Fprintf(w, "G90 (Absolute positioning)\n")
		fmt.Fprintf(w, "G17 (XY plane)\n")
		fmt.Fprintf(w, "G40 (Cancel cutter compensation)\n")
		fmt.Fprintf(w, "G49 (Cancel tool length offset)\n")
		fmt.Fprintf(w, "\n")
	}

	writeFooter := func(w *strings.Builder) {
		fmt.Fprintf(w, "G0 Z%.4f (Retract to safe height)\n", p.SafeZ)
		fmt.Fprintf(w, "M5 (Spindle off)\n")
		fmt.Fprintf(w, "G0 X0 Y0 (Return to origin)\n")
		fmt.Fprintf(w, "M30 (Program end)\n")
		fmt.Fprintf(w, "%%\n")
	}

	// --- Combined file header ---
	writeHeader(&combined, "All Operations")

	// ========================================
	// TOOL 1: 1/4" Ball End Mill - Marble Holes
	// ========================================
	writeHeader(&ballEnd, fmt.Sprintf("Ball End Mill %.4f\" - Marble Holes", p.BallEndDiameter))

	for _, w := range []*strings.Builder{&combined, &ballEnd} {
		fmt.Fprintf(w, "(=== TOOL 1: %.4f\" Ball End Mill - Marble Holes ===)\n", p.BallEndDiameter)
		fmt.Fprintf(w, "T1 M6 (Tool change: 1/4\" Ball End Mill)\n")
		fmt.Fprintf(w, "M3 S%d (Spindle on)\n", p.SpindleSpeed)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.SafeZ)
		fmt.Fprintf(w, "\n")
	}

	// Generate marble holes sorted by type for efficiency
	holeGroups := []struct {
		name  string
		htype HoleType
	}{
		{"Center Hole", HoleCenter},
		{"Home Row Holes", HoleHomeRow},
		{"Track Holes", HoleTrack},
		{"Start Position Holes", HoleStart},
		{"Base Holes", HoleBase},
	}

	for _, group := range holeGroups {
		holes := filterHoles(board.Holes, group.htype)
		if len(holes) == 0 {
			continue
		}

		for _, w := range []*strings.Builder{&combined, &ballEnd} {
			fmt.Fprintf(w, "(--- %s: %d holes ---)\n", group.name, len(holes))
		}

		for i, hole := range holes {
			comment := fmt.Sprintf("Hole %d/%d %s", i+1, len(holes), group.name)
			if hole.Player >= 0 {
				comment += fmt.Sprintf(" P%d", hole.Player+1)
			}
			gcodeMarbleHole(&combined, hole, p, comment)
			gcodeMarbleHole(&ballEnd, hole, p, comment)
		}
	}

	for _, w := range []*strings.Builder{&combined, &ballEnd} {
		fmt.Fprintf(w, "\nG0 Z%.4f (Retract)\n", p.SafeZ)
		fmt.Fprintf(w, "M5 (Spindle off)\n\n")
	}
	writeFooter(&ballEnd)

	// ========================================
	// TOOL 2: 1/8" Straight Bit - Dice Pockets
	// ========================================
	writeHeader(&straight, fmt.Sprintf("Straight Bit %.4f\" - Dice Pockets", p.StraightDiameter))

	for _, w := range []*strings.Builder{&combined, &straight} {
		fmt.Fprintf(w, "(=== TOOL 2: %.4f\" Straight Bit - Dice Pockets ===)\n", p.StraightDiameter)
		fmt.Fprintf(w, "T2 M6 (Tool change: 1/8\" Straight Bit)\n")
		fmt.Fprintf(w, "M3 S%d (Spindle on)\n", p.SpindleSpeed)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.SafeZ)
		fmt.Fprintf(w, "\n")
	}

	for i, pocket := range board.DicePockets {
		comment := fmt.Sprintf("Dice Pocket %d", i+1)
		gcodeDicePocket(&combined, pocket, p, comment)
		gcodeDicePocket(&straight, pocket, p, comment)
	}

	for _, w := range []*strings.Builder{&combined, &straight} {
		fmt.Fprintf(w, "\nG0 Z%.4f (Retract)\n", p.SafeZ)
		fmt.Fprintf(w, "M5 (Spindle off)\n\n")
	}
	writeFooter(&straight)

	// ========================================
	// TOOL 3: 60° V-Bit - Text Engraving
	// ========================================
	writeHeader(&vbit, fmt.Sprintf("%.0f° V-Bit - Text Engraving", p.VBitAngle))

	for _, w := range []*strings.Builder{&combined, &vbit} {
		fmt.Fprintf(w, "(=== TOOL 3: %.0f° V-Bit - Text Engraving ===)\n", p.VBitAngle)
		fmt.Fprintf(w, "T3 M6 (Tool change: 60 degree V-Bit)\n")
		fmt.Fprintf(w, "M3 S%d (Spindle on)\n", p.SpindleSpeed)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.SafeZ)
		fmt.Fprintf(w, "\n")
	}

	for _, text := range board.TextItems {
		strokes := TextToStrokes(text.Text, text.X, text.Y, text.Height, text.CenterOn)
		comment := fmt.Sprintf("Text: \"%s\"", text.Text)

		for _, w := range []*strings.Builder{&combined, &vbit} {
			fmt.Fprintf(w, "(%s)\n", comment)
		}

		for _, stroke := range strokes {
			if len(stroke) < 2 {
				continue
			}
			for _, w := range []*strings.Builder{&combined, &vbit} {
				// Rapid to start of stroke
				fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", stroke[0].X, stroke[0].Y)
				fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
				fmt.Fprintf(w, "G1 Z%.4f F%.1f\n", -p.TextDepth, p.FeedRateZ)
				// Cut along stroke
				for j := 1; j < len(stroke); j++ {
					fmt.Fprintf(w, "G1 X%.4f Y%.4f F%.1f\n", stroke[j].X, stroke[j].Y, p.FeedRateXY)
				}
				// Retract
				fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
			}
		}
	}

	for _, w := range []*strings.Builder{&combined, &vbit} {
		fmt.Fprintf(w, "\n")
	}
	writeFooter(&vbit)
	writeFooter(&combined)

	out.Combined = combined.String()
	out.BallEnd = ballEnd.String()
	out.Straight = straight.String()
	out.VBit = vbit.String()

	return out
}

// gcodeMarbleHole generates G-code for a single marble hole using helical bore.
func gcodeMarbleHole(w *strings.Builder, hole Hole, p Params, comment string) {
	toolRadius := p.BallEndDiameter / 2
	holeRadius := hole.Diameter / 2
	pocketRadius := holeRadius - toolRadius
	depth := hole.Depth

	fmt.Fprintf(w, "(%s at X%.4f Y%.4f D%.4f Z%.4f)\n", comment, hole.X, hole.Y, hole.Diameter, -depth)

	if pocketRadius <= 0.005 {
		// Hole is same size or smaller than tool - simple plunge bore
		fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", hole.X, hole.Y)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)

		// Plunge in passes
		currentZ := 0.0
		for currentZ > -depth {
			currentZ -= p.DepthPerPass
			if currentZ < -depth {
				currentZ = -depth
			}
			fmt.Fprintf(w, "G1 Z%.4f F%.1f\n", currentZ, p.FeedRateZ)
		}
		// Dwell briefly at bottom for clean cut
		fmt.Fprintf(w, "G4 P0.5 (Dwell)\n")
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
	} else {
		// Helical bore - tool traces circle while descending
		startX := hole.X + pocketRadius
		startY := hole.Y

		fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", startX, startY)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
		fmt.Fprintf(w, "G1 Z0.0 F%.1f\n", p.FeedRateZ)

		// Helical passes - each full circle descends by DepthPerPass
		currentZ := 0.0
		for currentZ > -depth {
			nextZ := currentZ - p.DepthPerPass
			if nextZ < -depth {
				nextZ = -depth
			}

			// Full circle with descent (G3 = CCW)
			// I, J are incremental from current position to center
			fmt.Fprintf(w, "G3 X%.4f Y%.4f I%.4f J%.4f Z%.4f F%.1f\n",
				startX, startY,
				-pocketRadius, 0.0,
				nextZ, p.FeedRateXY)

			currentZ = nextZ
		}

		// Spring pass at final depth (full circle, no Z change) for clean finish
		fmt.Fprintf(w, "G3 X%.4f Y%.4f I%.4f J%.4f F%.1f\n",
			startX, startY,
			-pocketRadius, 0.0,
			p.FeedRateXY)

		// Retract from center
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
	}
}

// gcodeDicePocket generates G-code for a rectangular pocket.
func gcodeDicePocket(w *strings.Builder, pocket DicePocket, p Params, comment string) {
	toolRadius := p.StraightDiameter / 2
	stepover := p.StraightDiameter * p.PocketStepover

	halfW := pocket.Width / 2
	halfH := pocket.Height / 2

	fmt.Fprintf(w, "(%s at X%.4f Y%.4f W%.4f H%.4f D%.4f)\n",
		comment, pocket.CenterX, pocket.CenterY, pocket.Width, pocket.Height, -pocket.Depth)

	// Rectangular pocket using offset passes from center outward
	// Multiple depth passes
	currentZ := 0.0
	for currentZ > -pocket.Depth {
		currentZ -= p.DepthPerPass
		if currentZ < -pocket.Depth {
			currentZ = -pocket.Depth
		}

		fmt.Fprintf(w, "(Depth pass Z%.4f)\n", currentZ)

		// Start at center, spiral outward in rectangular passes
		maxOffX := halfW - toolRadius
		maxOffY := halfH - toolRadius

		if maxOffX <= 0 || maxOffY <= 0 {
			// Pocket is too small for tool, just slot through
			fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", pocket.CenterX, pocket.CenterY)
			fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
			fmt.Fprintf(w, "G1 Z%.4f F%.1f\n", currentZ, p.FeedRateZ)
			fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
			continue
		}

		// Position at center for first pass
		fmt.Fprintf(w, "G0 X%.4f Y%.4f\n", pocket.CenterX, pocket.CenterY)
		fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
		fmt.Fprintf(w, "G1 Z%.4f F%.1f\n", currentZ, p.FeedRateZ)

		// Offset passes from center outward
		offX := stepover
		offY := stepover
		for offX <= maxOffX || offY <= maxOffY {
			if offX > maxOffX {
				offX = maxOffX
			}
			if offY > maxOffY {
				offY = maxOffY
			}

			cx := pocket.CenterX
			cy := pocket.CenterY

			// Rectangle pass (CCW): bottom-left -> bottom-right -> top-right -> top-left -> close
			fmt.Fprintf(w, "G1 X%.4f Y%.4f F%.1f\n", cx-offX, cy-offY, p.FeedRateXY)
			fmt.Fprintf(w, "G1 X%.4f Y%.4f\n", cx+offX, cy-offY)
			fmt.Fprintf(w, "G1 X%.4f Y%.4f\n", cx+offX, cy+offY)
			fmt.Fprintf(w, "G1 X%.4f Y%.4f\n", cx-offX, cy+offY)
			fmt.Fprintf(w, "G1 X%.4f Y%.4f\n", cx-offX, cy-offY)

			if offX >= maxOffX && offY >= maxOffY {
				break
			}
			offX += stepover
			offY += stepover
		}
	}

	fmt.Fprintf(w, "G0 Z%.4f\n", p.ClearanceZ)
}

// filterHoles returns holes matching the given type.
func filterHoles(holes []Hole, htype HoleType) []Hole {
	var result []Hole
	for _, h := range holes {
		if h.Type == htype {
			result = append(result, h)
		}
	}
	return result
}

// GenerateSVG creates an SVG preview of the board layout.
func GenerateSVG(board *Board) string {
	p := board.Params
	margin := 0.5 // SVG margin in inches

	var minX, minY, maxX, maxY float64
	if p.CenterOrigin {
		halfBoard := p.BoardSize / 2
		minX, minY = -halfBoard, -halfBoard
		maxX, maxY = halfBoard, halfBoard
	} else {
		minX, minY = 0, 0
		maxX, maxY = p.BoardSize, p.BoardSize
	}

	// SVG dimensions (pixels, 72 dpi)
	scale := 500.0 / (maxX - minX + 2*margin) // fit in 500px
	svgW := (maxX - minX + 2*margin) * scale
	svgH := (maxY - minY + 2*margin) * scale

	toSvgX := func(x float64) float64 { return (x - minX + margin) * scale }
	toSvgY := func(y float64) float64 { return svgH - (y-minY+margin)*scale } // flip Y

	var sb strings.Builder
	fmt.Fprintf(&sb, `<svg xmlns="http://www.w3.org/2000/svg" width="%.0f" height="%.0f" viewBox="0 0 %.0f %.0f">`, svgW, svgH, svgW, svgH)
	fmt.Fprintf(&sb, "\n")

	// Background (board)
	fmt.Fprintf(&sb, `<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" fill="#D4A574" stroke="#8B6914" stroke-width="2" rx="10"/>`,
		toSvgX(minX+p.BoardMargin/2), toSvgY(maxY-p.BoardMargin/2),
		(p.BoardSize-p.BoardMargin)*scale, (p.BoardSize-p.BoardMargin)*scale)
	fmt.Fprintf(&sb, "\n")

	// Hole colors by type
	holeColor := map[HoleType]string{
		HoleTrack:   "#4A4A4A",
		HoleBase:    "#2196F3",
		HoleHomeRow: "#4CAF50",
		HoleCenter:  "#FF9800",
		HoleStart:   "#F44336",
	}

	// Player colors for bases
	playerColor := []string{"#E53935", "#1E88E5", "#43A047", "#FDD835", "#AB47BC", "#FF7043"}

	// Draw holes
	for _, hole := range board.Holes {
		sx := toSvgX(hole.X)
		sy := toSvgY(hole.Y)
		sr := (hole.Diameter / 2) * scale

		color := holeColor[hole.Type]
		if hole.Type == HoleBase && hole.Player >= 0 && hole.Player < len(playerColor) {
			color = playerColor[hole.Player]
		}

		fmt.Fprintf(&sb, `<circle cx="%.1f" cy="%.1f" r="%.1f" fill="%s" stroke="#333" stroke-width="1" opacity="0.8"/>`,
			sx, sy, math.Max(sr, 3), color)
		fmt.Fprintf(&sb, "\n")
	}

	// Draw dice pockets
	for _, dp := range board.DicePockets {
		sx := toSvgX(dp.CenterX - dp.Width/2)
		sy := toSvgY(dp.CenterY + dp.Height/2)
		sw := dp.Width * scale
		sh := dp.Height * scale
		fmt.Fprintf(&sb, `<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" fill="#666" stroke="#333" stroke-width="1" rx="3"/>`,
			sx, sy, sw, sh)
		fmt.Fprintf(&sb, "\n")
	}

	// Draw text items (simplified - just labels)
	for _, text := range board.TextItems {
		sx := toSvgX(text.X)
		sy := toSvgY(text.Y)
		fontSize := text.Height * scale * 0.6
		anchor := "start"
		if text.CenterOn {
			anchor = "middle"
		}
		fmt.Fprintf(&sb, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="%.1f" fill="#333" text-anchor="%s">%s</text>`,
			sx, sy, fontSize, anchor, text.Text)
		fmt.Fprintf(&sb, "\n")
	}

	// Legend
	legendX := 10.0
	legendY := svgH - 100
	legends := []struct {
		color, label string
	}{
		{"#4A4A4A", "Track"},
		{"#F44336", "Start"},
		{"#4CAF50", "Home Row"},
		{"#FF9800", "Center"},
		{"#2196F3", "Base"},
	}
	for i, leg := range legends {
		y := legendY + float64(i)*18
		fmt.Fprintf(&sb, `<rect x="%.0f" y="%.0f" width="12" height="12" fill="%s"/>`, legendX, y, leg.color)
		fmt.Fprintf(&sb, `<text x="%.0f" y="%.0f" font-family="sans-serif" font-size="11" fill="#333">%s</text>`, legendX+16, y+10, leg.label)
		fmt.Fprintf(&sb, "\n")
	}

	fmt.Fprintf(&sb, `<text x="%.0f" y="%.0f" font-family="sans-serif" font-size="11" fill="#666">Holes: %d | Board: %.0f"x%.0f"</text>`,
		legendX, legendY-10, len(board.Holes), p.BoardSize, p.BoardSize)
	fmt.Fprintf(&sb, "\n")

	fmt.Fprintf(&sb, "</svg>")
	return sb.String()
}
